services:
    mysqldb:
        build: .
        container_name: mysql_all
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=ronivai
        ports:
            - 3306:3306
        volumes:
            - db:/var/lib/mysql
        networks:
            - nginx_network
        healthcheck:
            test: mysql -uroot -pronivai -e 'select 1'
    phpmyadmin:
        depends_on:
            mysqldb:
                condition: service_healthy
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 9090:80
        environment:
            PMA_HOST: mysqldb
            MYSQL_ROOT_PASSWORD: ronivai
            UPLOAD_LIMIT: 3000M
        networks:
            - nginx_network
networks:
    nginx_network:
volumes:
    db: